# Generated by Django 5.0.14 on 2026-08-10 15:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=40, unique=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, default='', max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenancy.tenancy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_date',),
                'indexes': [models.Index(fields=['tenant', '-transaction_date'], name='payments_pa_tenant__151359_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
